# Generated by Django 5.0.9 on 2024-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_os_manager', '0002_goldenimage_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsdevicetype',
            name='version_cli_show_command',
            field=models.CharField(default='show version', max_length=255),
        ),
        migrations.AddField(
            model_name='settingsdevicetype',
            name='version_regex_group_index',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='settingsdevicetype',
            name='version_regex_search',
            field=models.CharField(default='(?:Version|System version)\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+)', max_length=255),
        ),
    ]
